### ISSUE TITLE
QE Load balancer v1 refactored API documentation

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#161]
# Refactor API Guide: QE checklist for v1

Use the following checklist to verify the API guide refactoring for Load Balancers, v1. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
@meker12 - Differences found using Text Wrangler between the 2 conf.py files as shown below. Most of the differences are in comments, with template conf.py have an underscore (_) at the beginning of the line, while  CLB conf.py did not have it. Only a few differences of real interest such as the following ones:  
- addition of extlinks for rax-cart and rax-special and change for rax-devguide and rax-api
- addition of |service| to rst-epilog
- html_add_permalinks commented out in CLB conf.py
- latex-elements not commented out in CLB conf.py
- under man-pages, CLB conf.py still as API Developer Guide rather than Rackspace Product API documentation
-


Nonmatching Lines (File untitled text; Line 3; File untitled text; Line 3)
Nonmatching Lines (File untitled text; Line 15:17; File untitled text; Line 15:23)
Nonmatching Lines (File untitled text; Line 22; File untitled text; Line 28)
Nonmatching Lines (File untitled text; Line 27; File untitled text; Line 33)
Extra lines in Right before 41 in Left (File untitled text; Line 41; File untitled text; Line 47:49)
Nonmatching Lines (File untitled text; Line 42; File untitled text; Line 51)
Nonmatching Lines (File untitled text; Line 50; File untitled text; Line 59)
Nonmatching Lines (File untitled text; Line 57; File untitled text; Line 66)
Nonmatching Lines (File untitled text; Line 60:61; File untitled text; Line 69:70)
Nonmatching Lines (File untitled text; Line 69; File untitled text; Line 78)
Nonmatching Lines (File untitled text; Line 71; File untitled text; Line 80)
Nonmatching Lines (File untitled text; Line 84; File untitled text; Line 93)
Nonmatching Lines (File untitled text; Line 88:89; File untitled text; Line 97:99)
Nonmatching Lines (File untitled text; Line 93; File untitled text; Line 103)
Nonmatching Lines (File untitled text; Line 96; File untitled text; Line 106)
Nonmatching Lines (File untitled text; Line 100; File untitled text; Line 110)
Nonmatching Lines (File untitled text; Line 104; File untitled text; Line 114)
Extra lines in Right before 112 in Left (File untitled text; Line 112; File untitled text; Line 122:123)
Nonmatching Lines (File untitled text; Line 115; File untitled text; Line 127)
Nonmatching Lines (File untitled text; Line 117; File untitled text; Line 129)
Nonmatching Lines (File untitled text; Line 132; File untitled text; Line 144:145)
Nonmatching Lines (File untitled text; Line 135:138; File untitled text; Line 148:153)
Nonmatching Lines (File untitled text; Line 141:142; File untitled text; Line 156:157)
Nonmatching Lines (File untitled text; Line 145; File untitled text; Line 160)
Nonmatching Lines (File untitled text; Line 148; File untitled text; Line 163)
Nonmatching Lines (File untitled text; Line 158; File untitled text; Line 173:177)
Nonmatching Lines (File untitled text; Line 163; File untitled text; Line 182)
Nonmatching Lines (File untitled text; Line 166; File untitled text; Line 185)
Nonmatching Lines (File untitled text; Line 170; File untitled text; Line 189)
Nonmatching Lines (File untitled text; Line 173; File untitled text; Line 192)
Nonmatching Lines (File untitled text; Line 177; File untitled text; Line 196)
Nonmatching Lines (File untitled text; Line 182; File untitled text; Line 201)
Nonmatching Lines (File untitled text; Line 187; File untitled text; Line 206)
Nonmatching Lines (File untitled text; Line 192; File untitled text; Line 211)
Nonmatching Lines (File untitled text; Line 201; File untitled text; Line 220)
Nonmatching Lines (File untitled text; Line 204; File untitled text; Line 223)
Nonmatching Lines (File untitled text; Line 208; File untitled text; Line 227)
Nonmatching Lines (File untitled text; Line 211; File untitled text; Line 230)
Nonmatching Lines (File untitled text; Line 214; File untitled text; Line 233)
Nonmatching Lines (File untitled text; Line 217; File untitled text; Line 236)
Nonmatching Lines (File untitled text; Line 220; File untitled text; Line 239)
Nonmatching Lines (File untitled text; Line 223; File untitled text; Line 242)
Nonmatching Lines (File untitled text; Line 226; File untitled text; Line 245)
Nonmatching Lines (File untitled text; Line 231; File untitled text; Line 250)
Nonmatching Lines (File untitled text; Line 234; File untitled text; Line 253)
Nonmatching Lines (File untitled text; Line 240; File untitled text; Line 259)
Nonmatching Lines (File untitled text; Line 244; File untitled text; Line 263)
Nonmatching Lines (File untitled text; Line 248; File untitled text; Line 267)
Nonmatching Lines (File untitled text; Line 251; File untitled text; Line 270)
Nonmatching Lines (File untitled text; Line 254; File untitled text; Line 273)
Nonmatching Lines (File untitled text; Line 258; File untitled text; Line 277)
Nonmatching Lines (File untitled text; Line 260; File untitled text; Line 279)
Nonmatching Lines (File untitled text; Line 263; File untitled text; Line 282)
Nonmatching Lines (File untitled text; Line 266; File untitled text; Line 285)
Nonmatching Lines (File untitled text; Line 269:270; File untitled text; Line 288:289)
Nonmatching Lines (File untitled text; Line 276:278; File untitled text; Line 295:297)
Nonmatching Lines (File untitled text; Line 283; File untitled text; Line 302)
Nonmatching Lines (File untitled text; Line 287; File untitled text; Line 306)
Nonmatching Lines (File untitled text; Line 290; File untitled text; Line 309)
Nonmatching Lines (File untitled text; Line 293; File untitled text; Line 312)
Nonmatching Lines (File untitled text; Line 296; File untitled text; Line 315)
Nonmatching Lines (File untitled text; Line 299; File untitled text; Line 318)
Nonmatching Lines (File untitled text; Line 307; File untitled text; Line 326:327)
Nonmatching Lines (File untitled text; Line 312; File untitled text; Line 332)
Nonmatching Lines (File untitled text; Line 321:322; File untitled text; Line 341:342)
Nonmatching Lines (File untitled text; Line 327; File untitled text; Line 347)
Nonmatching Lines (File untitled text; Line 330; File untitled text; Line 350)
Nonmatching Lines (File untitled text; Line 333; File untitled text; Line 353)
Nonmatching Lines (File untitled text; Line 336:342; File untitled text; Line 356)

**Comment by cyrichardson** [comment]
@meker12 Minor differences found between the 2 authenticate.rst files using Text Wrangler to compare files:

Extra lines in Right before 3 in Left (File authenticate.rst; Line 3; File authenticate.rst; Line 3)
Nonmatching Lines (File authenticate.rst; Line 4; File authenticate.rst; Line 5)
Nonmatching Lines (File authenticate.rst; Line 6:11; File authenticate.rst; Line 7:11)
Nonmatching Lines (File authenticate.rst; Line 26; File authenticate.rst; Line 26)
Nonmatching Lines (File authenticate.rst; Line 29:30; File authenticate.rst; Line 29)
Nonmatching Lines (File authenticate.rst; Line 32; File authenticate.rst; Line 31)
Nonmatching Lines (File authenticate.rst; Line 35:36; File authenticate.rst; Line 34:35)
Nonmatching Lines (File authenticate.rst; Line 38; File authenticate.rst; Line 37)

**Comment by cyrichardson** [comment]
There are also small differences between the other files included in the auth section in the 2 repos - looks like maybe Kelly's editing changes.

**Comment by cyrichardson** [comment]
@meker12 General API topics differ between load balancers v1 repo and docs-common repo. The ones in the LB v1 repo are about a month older than those in the docs-common repo. They don't have the changes for the wrap at 79 characters changes, the table directive changes, and changes making the heading syntax marker end at end of the title words.

**Comment by cyrichardson** [comment]
Comparing conf.py using Text Wrangler differences,  differences are product specific except for the following:
- CLB shows html_use_smartyparts=True commented out
- CLB shows html_add_permlinks='#' commented out
- CLB shows 'API Developer Guide' rather than 'Rackspace Cloud Load Balancers API documentation in man_pages
- CLB shows 'Rackspace Cloud Load Balancers API Developer Guide' rather than 'Rackspace Cloud Load Balancers API Documentation' in texinfo_documents

**Comment by cyrichardson** [comment]
Comparing authentication section files, these differences exist: 

In authenticate_using_curl:
- Line 6 - need "an" before authentication
- Line 17 - need "," after <get-credentials>
- Lines 31 through 33 - start with capital letter
- Line 38 - "request and response" on same line in link
-  After Line 53 in template file, missing code 400 and 401 info
- Line 97 - change "prior to" to "before"
- Line 99 - change "tokens and token expiration" to "authentication tokens"
- Line 105 - "Services" to "services"

Moved to create PR against the meker12 repo after this... to include the changes above and any other for this file.

**Comment by cyrichardson** [comment]
@meker12 All done with QE checklist. Made PRs for all fill differentces except for the conf.py one... wasn't sure how smartypants and permalinks should be set.
